# Generated by Django 5.2.8 on 2025-11-29 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry_type', models.CharField(blank=True, choices=[('Point', 'Point'), ('LineString', 'LineString'), ('Polygon', 'Polygon'), ('MultiPoint', 'MultiPoint'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon')], max_length=50)),
                ('shapefile', models.FileField(help_text='Upload .shp file', upload_to='shapefiles/')),
                ('shx_file', models.FileField(blank=True, null=True, upload_to='shapefiles/')),
                ('dbf_file', models.FileField(blank=True, null=True, upload_to='shapefiles/')),
                ('prj_file', models.FileField(blank=True, null=True, upload_to='shapefiles/')),
                ('geojson_data', models.JSONField(blank=True, null=True)),
                ('feature_count', models.IntegerField(default=0)),
                ('srid', models.IntegerField(default=4326, help_text='Spatial Reference System ID')),
                ('bounds', models.JSONField(blank=True, help_text='Bounding box [minx, miny, maxx, maxy]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shapefiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Layer',
                'verbose_name_plural': 'Shapefile Layers',
                'ordering': ['-created_at'],
            },
        ),
    ]
