# Generated by Django 5.2.8 on 2025-11-30 17:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(db_index=True, unique=True)),
                ('osm_type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('perimeter', models.FloatField(blank=True, null=True)),
                ('amenity', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('healthcare', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('health_amenity', models.CharField(blank=True, db_column='health_ame', max_length=100, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_type', models.CharField(blank=True, db_column='operator_t', max_length=100, null=True)),
                ('operational_status', models.CharField(blank=True, db_column='operationa', max_length=100, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('staff_doctors', models.IntegerField(blank=True, db_column='staff_doct', null=True)),
                ('staff_nurses', models.IntegerField(blank=True, db_column='staff_nurs', null=True)),
                ('dispensing', models.CharField(blank=True, max_length=50, null=True)),
                ('wheelchair', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('water_source', models.CharField(blank=True, db_column='water_sour', max_length=100, null=True)),
                ('electricity', models.CharField(blank=True, db_column='electricit', max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, db_column='opening_ho', max_length=255, null=True)),
                ('addr_housenumber', models.CharField(blank=True, db_column='addr_house', max_length=50, null=True)),
                ('addr_street', models.CharField(blank=True, db_column='addr_stree', max_length=255, null=True)),
                ('addr_postcode', models.CharField(blank=True, db_column='addr_postc', max_length=20, null=True)),
                ('addr_city', models.CharField(blank=True, db_column='addr_city', max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('completeness', models.FloatField(blank=True, db_column='completene', null=True)),
                ('changeset_id', models.BigIntegerField(blank=True, db_column='changeset_', null=True)),
                ('changeset_version', models.IntegerField(blank=True, db_column='changese_1', null=True)),
                ('changeset_timestamp', models.CharField(blank=True, db_column='changese_2', max_length=50, null=True)),
                ('is_in_health_system', models.CharField(blank=True, db_column='is_in_heal', max_length=100, null=True)),
                ('is_in_health_system_1', models.CharField(blank=True, db_column='is_in_he_1', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
                'db_table': 'health_facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['district', 'amenity'], name='health_faci_distric_8d1221_idx'), models.Index(fields=['region', 'district'], name='health_faci_region_0d4e9e_idx')],
            },
        ),
    ]
